name: walle
channels:
  - anaconda
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
  - salilab
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abnumber=0.3.2
  - anarci=2020.04.23
  - argtable2=2.13
  - blas=1.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - clustalo=1.2.4
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-runtime=12.1.0
  - cudatoolkit=11.7.0
  - dssp=3.0.0
  - ffmpeg=4.3
  - fftw=3.3.10
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - hmmer=3.3.2
  - icu=58.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.3
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libboost=1.73.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numexpr=2.8.7
  - ocl-icd=2.3.2
  - ocl-icd-system=1.0.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openmm=7.7.0
  - openssl=3.2.1
  - pdbfixer=1.8.1
  - pillow=10.2.0
  - pip=23.3.1
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytorch=2.1.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=2.1.1
  - torchtriton=2.1.0
  - torchvision=0.16.1
  - tzdata=2024a
  - urllib3=2.1.0
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==2.1.0
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - antiberty==0.1.3
    - antlr4-python3-runtime==4.9.3
    - anyio==4.3.0
    - appdirs==1.4.4
    - async-timeout==4.0.3
    - attrs==23.2.0
    - beautifulsoup4==4.12.3
    - biopandas==0.5.1.dev0
    - biopython==1.83
    - bioservices==1.11.2
    - biovec==0.2.7
    - cattrs==23.2.3
    - click==8.1.7
    - colorama==0.4.6
    - colorlog==6.8.2
    - contourpy==1.2.1
    - cycler==0.12.1
    - deepdiff==7.0.1
    - dnspython==2.6.1
    - docker==7.0.0
    - docker-pycreds==0.4.0
    - easydev==0.13.1
    - einops==0.7.0
    - exceptiongroup==1.2.1
    - fair-esm==2.0.0
    - foldcomp==0.0.7
    - fonttools==4.51.0
    - frozenlist==1.4.1
    - fsspec==2024.3.1
    - gdown==5.0.1
    - gensim==3.4.0
    - gevent==24.2.1
    - gitdb==4.0.11
    - gitpython==3.1.43
    - graphein==1.7.6
    - greenlet==3.0.3
    - grequests==0.7.0
    - grpcio==1.62.2
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.22.2
    - hydra-core==1.3.2
    - igfold==0.4.0
    - jaxtyping==0.2.28
    - joblib==1.4.0
    - kiwisolver==1.4.5
    - lightning-utilities==0.11.2
    - line-profiler==4.1.2
    - loguru==0.7.2
    - looseversion==1.1.2
    - lxml==5.2.1
    - markdown==3.6
    - markdown-it-py==3.0.0
    - matplotlib==3.8.4
    - mdurl==0.1.2
    - mmtf-python==1.1.3
    - mpl-chord-diagram==0.3.2
    - msgpack==1.0.8
    - multidict==6.0.5
    - multipledispatch==1.0.0
    - mypy-extensions==1.0.0
    - nest-asyncio==1.6.0
    - numpy==1.23.5
    - omegaconf==2.3.0
    - ordered-set==4.1.0
    - packaging==24.0
    - pandas==1.5.3
    - pexpect==4.9.0
    - platformdirs==4.2.0
    - plotly==5.21.0
    - propy3==1.1.1
    - protobuf==4.25.3
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pyaaisc==1.2
    - pydantic==1.10.15
    - pyfasta==0.5.2
    - pygments==2.17.2
    - pymongo==4.6.3
    - pyparsing==3.1.2
    - pyprind==2.11.3
    - pyre-extensions==0.0.30
    - pytorch-lightning==1.8.6
    - rdkit==2023.9.5
    - regex==2024.4.16
    - requests-cache==1.2.0
    - rich==13.7.1
    - rich-click==1.7.4
    - safetensors==0.4.3
    - scikit-learn==1.4.2
    - scipy==1.13.0
    - seaborn==0.13.2
    - selfies==2.1.1
    - sentry-sdk==1.45.0
    - setproctitle==1.3.3
    - smart-open==7.0.4
    - smilite==2.3.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - soupsieve==2.5
    - suds-community==1.1.2
    - tabulate==0.9.0
    - tenacity==8.2.3
    - tensorboard==2.16.2
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.2.2
    - threadpoolctl==3.4.0
    - tokenizers==0.19.1
    - torch-geometric==2.5.3
    - torcheval==0.0.6
    - torchmetrics==1.3.2
    - torchtnt==0.2.3
    - tqdm==4.66.2
    - transformers==4.40.0
    - typeguard==2.13.3
    - typing-extensions==4.5.0
    - typing-inspect==0.9.0
    - url-normalize==1.4.3
    - wandb==0.16.6
    - werkzeug==3.0.2
    - wget==3.2
    - wrapt==1.16.0
    - xarray==2024.3.0
    - xmltodict==0.13.0
    - yarl==1.9.4
    - zope-event==5.0
    - zope-interface==6.3
    - "pyg_lib           @ https://data.pyg.org/whl/torch-2.1.0%2Bcu121/pyg_lib-0.4.0%2Bpt21cu121-cp310-cp310-linux_x86_64.whl"
    - "torch_scatter     @ https://data.pyg.org/whl/torch-2.1.0%2Bcu121/torch_scatter-2.1.2%2Bpt21cu121-cp310-cp310-linux_x86_64.whl"
    - "torch_sparse      @ https://data.pyg.org/whl/torch-2.1.0%2Bcu121/torch_sparse-0.6.18%2Bpt21cu121-cp310-cp310-linux_x86_64.whl"
    - "torch_cluster     @ https://data.pyg.org/whl/torch-2.1.0%2Bcu121/torch_cluster-1.6.3%2Bpt21cu121-cp310-cp310-linux_x86_64.whl"
    - "torch_spline_conv @ https://data.pyg.org/whl/torch-2.1.0%2Bcu121/torch_spline_conv-1.2.2%2Bpt21cu121-cp310-cp310-linux_x86_64.whl"
