name: walle
channels:
  - pytorch
  - salilab
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abnumber=0.3.2
  - anarci=2020.04.23
  - argtable2=2.13
  - biopython=1.78
  - blas=1.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - clustalo=1.2.4
  - cudatoolkit=11.8.0
  - dssp=3.0.0
  - ffmpeg=4.3
  - fftw=3.3.10
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - hmmer=3.3.2
  - icu=58.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.3
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libboost=1.73.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - ocl-icd=2.3.2
  - ocl-icd-system=1.0.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openmm=7.7.0
  - openssl=3.2.1
  - pandas=2.1.1
  - pdbfixer=1.8.1
  - pillow=10.2.0
  - pip=23.3.1
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytorch=2.1.1
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=2.1.1
  - torchvision=0.16.1
  - typing_extensions=4.7.1
  - tzdata=2024a
  - urllib3=2.1.0
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - gdown==5.0.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.62.2
      - hydra-core==1.3.2
      - joblib==1.4.0
      - kiwisolver==1.4.5
      - markdown==3.6
      - matplotlib==3.8.4
      - multidict==6.0.5
      - omegaconf==2.3.0
      - packaging==24.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - pymongo==4.6.3
      - pyparsing==3.1.2
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - soupsieve==2.5
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.4.0
      - torch-geometric==2.5.3
      - torcheval==0.0.7
      - tqdm==4.66.2
      - wand==0.6.13
      - wandb==0.16.6
      - werkzeug==3.0.2
      - yarl==1.9.4
      - "pyg_lib           @ https://data.pyg.org/whl/torch-2.1.0%2Bcpu/pyg_lib-0.4.0%2Bpt21cpu-cp310-cp310-linux_x86_64.whl"
      - "torch_cluster     @ https://data.pyg.org/whl/torch-2.1.0%2Bcpu/torch_cluster-1.6.3%2Bpt21cpu-cp310-cp310-linux_x86_64.whl"
      - "torch_scatter     @ https://data.pyg.org/whl/torch-2.1.0%2Bcpu/torch_scatter-2.1.2%2Bpt21cpu-cp310-cp310-linux_x86_64.whl"
      - "torch_sparse      @ https://data.pyg.org/whl/torch-2.1.0%2Bcpu/torch_sparse-0.6.18%2Bpt21cpu-cp310-cp310-linux_x86_64.whl"
      - "torch_spline_conv @ https://data.pyg.org/whl/torch-2.1.0%2Bcpu/torch_spline_conv-1.2.2%2Bpt21cpu-cp310-cp310-linux_x86_64.whl"

